# Site settings
title: Go Cheatsheets
description: A comprehensive reference guide for Go programming language based on Go 1.24.1 documentation
baseurl: "/go-cheatsheets"
url: "https://goecosystem.github.io"
repository: GoEcosystem/go-cheatsheets

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: jekyll-theme-cayman

# Custom variables
github_username: GoEcosystem
github_repo: go-cheatsheets

# Navigation
navigation:
  - title: Home
    url: /
  - title: Basics
    url: /basics/
  - title: Advanced
    url: /advanced/
  - title: Concurrency
    url: /concurrency/
  - title: Standard Library
    url: /standard-library/
  - title: Tooling
    url: /tooling/
  - title: GitHub
    url: https://github.com/GoEcosystem/go-cheatsheets

# Jekyll settings
github:
  is_project_page: true
  repository_url: https://github.com/GoEcosystem/go-cheatsheets
  repository_name: go-cheatsheets
  owner_name: GoEcosystem
  owner_url: https://github.com/GoEcosystem

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - CNAME

# Enable GitHub Pages to render Markdown files
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - LICENSE

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "basics"
    values:
      layout: "cheatsheet"
  - scope:
      path: "advanced"
    values:
      layout: "cheatsheet"
  - scope:
      path: "concurrency"
    values:
      layout: "cheatsheet"
  - scope:
      path: "standard-library"
    values:
      layout: "cheatsheet"
  - scope:
      path: "tooling"
    values:
      layout: "cheatsheet"
