theme: jekyll-theme-cayman
title: Go Cheatsheets
description: Quick reference guides for Go programming language
show_downloads: false

plugins:
  - jekyll-relative-links

# Enable GitHub Pages to render Markdown files
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - LICENSE.md
